sudo: required
language: bash

services:
  - docker

before_script:
  - gem install asciibuild
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
  - asciibuild $ASCIIBUILD_OPTS -a publish README.adoc

env:
  global:
    - RIAK_KV_VERSION=2.1.4
    - RIAK_TS_VERSION=1.4.0
  matrix:
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a riak_flavor=kv -a riak_version=$RIAK_KV_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a riak_flavor=kv -a riak_version=$RIAK_KV_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=debian -a os_version=8 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
