sudo: required
language: bash

services:
  - docker

before_script:
  - gem install asciibuild

script:
  - asciibuild -a docker_user=$DOCKER_USER -a docker_password=$DOCKER_PASSWORD $ASCIIBUILD_OPTS README.adoc

env:
  matrix:
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a publish"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a publish"
  global:
    - secure: urpOJkUdw2+cvbCu3Upb/TYeUfMPiHJwxFqtnOppmpJRcgpvnlfQ+Ec7daO8bj//5FJf73zDXiOEjjTuARzVJafV1VAJqTGrUF/xL9ZLUZVY5WUJLazVx/8T9IiMI5lmOb08UD+IjvXrWQv2EX7fzM+jTvnzd0G/uVk5UKkj6R3r8dwvwEuSdfQ/vHATrkhG9RvLwpB8BT2K2V8ueWoKGlsInjjvVH/W9obPxbvDlCv0OnlTjMdOZmT3SPAHcwUg/fIIq8HlByiZmHTRgKvQ91CxaPYm4AgUlA57dyAToFv60jvkC+aF0L0nMXrFg4duVk2NUZIsuIu3CmlgQqTBaSfTre+7B+3eFIIy4x3OloL28ZuEr4Og7HmiEI2FByOJhUi4XX8jVChVLhp9yurGZ0AegUrFn+7/9roV7BD1wRuugCdJOBFZZUGPoKBFt8gPvcXnlo7X+BbJueLu1euLKbmJP3fLLmL3DsiUJ4etoui085fW2nGMLaFJfWu90AfzPI7xNMsQkgVrel8UpjnQ29IBF6xI9AqvzY7P5ekB7z5pv0OhJNHrHTWfywoBJgcg13korplFzGQ0n5Jj4lCSDiq1qM4+p5mPNMzfa4ragaF0GByqgkgFDeyPPrO6uHgd9zRsW5dzej2OiFo5MwViCdPbOEkPBumTEqpa3WnMz/Y=
    - secure: WGT8sLAFuD882BPnnPlA/qE/nVvU8mfYPcuHofsANX/DuQHBTR5G+bxrCczIGy9cfjy2hOMJpXB9slySMhOmJO1Ru2dloT6J5zEi+gYL3NGXJRfVeoXYaLjMm+wbmn+VclAH2P44Ui4GleUlxNcjxGU8bd45WaY7e4wZ7szuYyFPnnfFmzN2Tt+OJ0Ol0SARtoaAhh+ynoKl4ZFdU/cpGnB9Vkcsztond8Q5a9GeNmsOKPuDDZobHWJAQYUo68F1zODk+okKYYNztDcgCxNqt+3EFNGbbafKCa0EN75+jeKdwiXGTP13/11lDt4XKBYsLidfeYhudls5pKqWNg18G0R/XCgEpptidgdTzUkPXBTvbuUbD5aBunnWmJtYmtoFozDD7E1avgtUlAXrafrY48zH5NMNQ7+k/l97QKkhoLazcjExUxxKAK3xsgy6HgNEuBolhSSuyThnGOg3pU+LOOCDz7yzluGE5M8DFwH1+Xct9QCJw59yqez6anYB0qAkSoyPXJXbwhZDHLUzNDbKXDLtd7PP2FVeKYwMSN5SOT6Pzsn35ZBftqQ9FlJEqTypcz20p4VJYhCogyNoDTa2ZjiovROV8FS6VANP1wX7zlEbERbZw5N5kU9YzlDC4MJZLWpyrvVLN8BC5OcPZPVpjEJHHh6dnOeg//SI+tXW9EY=
