sudo: required
language: bash

services:
  - docker

before_script:
  - gem install asciibuild

script:
  - asciibuild $ASCIIBUILD_OPTS README.adoc

env:
  matrix:
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a publish"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a publish"
