sudo: required
language: bash

services:
  - docker

before_script:
  - gem install asciibuild
  - if [ "false" == "$TRAVIS_PULL_REQUEST" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD fi 

script:
  - asciibuild $ASCIIBUILD_OPTS -a skip_publish=$TRAVIS_PULL_REQUEST README.adoc

env:
  global:
    - RIAK_TS_VERSION=1.4.0
  matrix:
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a riak_flavor=kv -a riak_version=2.0.7"
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a riak_flavor=kv -a riak_version=2.0.7"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a riak_flavor=kv -a riak_version=2.1.4"
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a riak_flavor=kv -a riak_version=2.1.4"
    - ASCIIBUILD_OPTS="-a os_family=centos -a os_version=7 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=debian -a os_version=8 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
    - ASCIIBUILD_OPTS="-a os_family=ubuntu -a os_version=14.04 -a riak_flavor=ts -a riak_version=$RIAK_TS_VERSION"
